feat: Add RR crossing number to updated mobile and desktop menus
mbta/dotcom pull request #1199
Opened 2022-02-23 18:24 UTC by bfauble

#### Summary of changes
**Asana Ticket:** [Add RR crossing number to updated mobile and desktop menus](https://app.asana.com/0/385363666817452/1201782887147816/f)

Add the railroad crossing gate issue number to the new desktop and mobile menus.

![image](https://user-images.githubusercontent.com/526017/155382881-28b3ab8a-ff7f-421d-93c0-9ab514a937ca.png)
![image](https://user-images.githubusercontent.com/526017/155382921-7b7856a5-6365-4001-9d5b-636cb33cdf8d.png)
![image](https://user-images.githubusercontent.com/526017/155382940-90ce7615-fd26-4cd5-acd3-069482a90f42.png)

2022-02-23 21:20 UTC, thecristen requested changes
💯 on mobile/tablet view, thanks for the attention to white space/text wrapping.

The mock for the desktop view structures this new section a bit differently, placing it in the bottom of the center column instead of below the two sections in the right column. Can you update this to reflect that too?

2022-02-23 21:20 UTC, thecristen commented on apps/site/lib/site_web/views/helpers.ex
> +          class: "no-wrap",
👍🏼 Good addition.

2022-02-28 20:40 UTC, bfauble commented
https://www.w3.org/TR/css-grid-1/#repeat-syntax
https://www.w3.org/TR/css-grid-1/#valdef-repeat-auto-fit

couple relevant pieces of info regarding generating auto-fit columns

2022-02-28 20:46 UTC, thecristen approved these changes
Great!

2022-02-28 20:49 UTC, merged