Check if within range of glx opening date
mbta/dotcom pull request #1219
Opened 2022-03-08 21:23 UTC by bfauble

#### Summary of changes
**Asana Ticket:** [Store station opening dates and check age](https://app.asana.com/0/555089885850811/1201708898492590/f)

Added plug to set an assign within conn if the current date after the set opening date for the glx expansion and not more than 3 months after that date.

2022-03-08 21:36 UTC, thecristen commented on apps/site/lib/site_web/plugs/glx_now_open.ex
> +    after_open_date?(current_date, opening_date) && before_end_date?(current_date, opening_date)
Ha, technically `after_open_date?` can also be `Util.time_is_greater_or_equal?(current_date, opening_date)`

2022-03-09 15:23 UTC, thecristen requested changes
I found out this morning that this is confirmed to open at the start of service (e.g. very early morning). MBTA service dates are understood (in Dotcom's code, at least -- see `Util.service_date/1`) to run from 3am to 2:59am. Can you adjust the opening date time to 3am?

2022-03-09 15:56 UTC, bfauble commented
> I found out this morning that this is confirmed to open at the start of service (e.g. very early morning). MBTA service dates are understood (in Dotcom's code, at least -- see `Util.service_date/1`) to run from 3am to 2:59am. Can you adjust the opening date time to 3am?

updated to use 3am as the opening time, also tightened up tests to check those specific boundaries.

2022-03-09 20:36 UTC, thecristen approved these changes
⏲️

2022-03-09 21:52 UTC, merged