Always render acccessibility icon for bus stops
mbta/dotcom pull request #1244
Opened 2022-03-21 16:53 UTC by zovt

#### Summary of changes
**Asana Ticket:** [Show accessibility icon for all bus stops](https://app.asana.com/0/385363666817452/1201894234147725/f)

This PR updates the gating logic for the accessibility icons to always render for bus routes. The following locations have been updated:
- Line Diagram
- Stop pages (both the header and the nearby transfers)
- Transit Near Me

I decided to tackle this on the front end since I figured it was more of a rendering concern, and didn't want to muck with any of the accessibility data we return from the back end.

I did some light testing, and don't believe that these changes should have any unexpected side effects, but let me know if there is a cleaner approach for any of these.

2022-03-21 18:04 UTC, thecristen requested changes
Let's add a helper function, maybe `routeHasBusStop()`, that could return the boolean for all these different scenarios (taking in `TypedRoutes[]`, `RouteWithDirection[]`, `RouteStop`, `Route`).

2022-03-21 19:45 UTC, zovt commented
@thecristen 

> Let's add a helper function, maybe `routeHasBusStop()`, that could return the boolean for all these different scenarios (taking in `TypedRoutes[]`, `RouteWithDirection[]`, `RouteStop`, `Route`).

I think the different scenarios have a different enough meaning that they warrant separately-named functions (plus the type punning necessary for the arrays is pretty ugly), but I've colocated all of them into a single file in `helpers`. There's another `route` file in `models`, but the function signatures need to pull in some types from separate locations and I didn't want to pollute that file with those. 

Let me know what you think!

2022-03-22 12:19 UTC, thecristen commented on apps/site/assets/ts/helpers/routes.ts
> +}
Are these similar enough to be rewritten into one function using Typescript's function overloading? See example here https://dmitripavlutin.com/typescript-function-overloading/

2022-03-22 15:22 UTC, thecristen approved these changes

2022-03-22 15:33 UTC, merged