Departure times out of order fix
mbta/dotcom pull request #1290
Opened 2022-04-29 19:01 UTC by i0sea

#### Summary of changes
**Asana Ticket:** [Departure times out of order](https://app.asana.com/0/555089885850811/1201990508147605/f)

Put departure times in order by comparing prediction times.

2022-05-03 01:01 UTC, thecristen requested changes
A few small things

2022-05-03 01:01 UTC, thecristen commented on apps/site/assets/ts/components/__tests__/HeadsignTest.tsx
> +  expect(tree).toMatchSnapshot();
suggestion (non-blocking): While the snapshot does show the predictions in the corrected order, I think an approach that renders the component, finds the displayed numbers, and makes the assertion that the first one is less than the second one (e.g. `expect(first).toBeLessThan(second)`, would be helpful here.

2022-05-03 15:18 UTC, i0sea commented on apps/site/assets/ts/components/Headsign.tsx
> +        (first > second && first !== "arriving") ||
Time strings can be compared directly if they're in 24 hour format or in the same format. I'll concat AM/PM onto them to avoid afternoon issues.

2022-05-03 15:21 UTC, i0sea commented on apps/site/assets/ts/components/Headsign.tsx
> +        second === "arrriving"
Couldn't there be a case where first > second and first and second are in HH:mm format?

2022-05-03 16:35 UTC, thecristen commented on apps/site/assets/ts/components/Headsign.tsx
> +        (first > second && first !== "arriving") ||
ahh I see. Yeah definitely want to avoid afternoon issues.

2022-05-03 16:42 UTC, thecristen commented on apps/site/assets/ts/components/Headsign.tsx
> +        second === "arrriving"
Ah yeah, that's right -- sorry, didn't realize that's what you were getting at with the `first !== "arriving"` piece

2022-05-03 18:20 UTC, thecristen commented on apps/site/assets/ts/components/Headsign.tsx
> +        (first.concat(firstMeridiem) > second.concat(secondMeridiem) && first !== "arriving") ||
This works a lot of the time but I am concerned about edge cases. For example, `"9:11AM" > "10:04AM"` will evaluate `true` and get reversed here 🤔

2022-05-06 17:31 UTC, thecristen reviewed
Did you look at the coverage output for this file?

<img width="626" alt="image" src="https://user-images.githubusercontent.com/2136286/167182703-c1eed6a2-c8d6-4422-8348-4d014fedf3fc.png">

It's highlighting the untested piece in red -- part of the last `else if` isn't covered
```
else if (
         (Date.parse(first.concat(firstMeridiem)) >
           Date.parse(second.concat(secondMeridiem)) &&
           first !== "arriving") ||
         second === "arriving"
       ) {
         headsign.times.reverse();
       }
```

2022-05-06 17:52 UTC, i0sea commented
@thecristen How do you get this coverage report? Do I open `apps/site/assets/ts/coverage/index.html` in the browser or is this somewhere else?

2022-05-06 17:57 UTC, thecristen commented
> @thecristen How do you get this coverage report? Do I open `apps/site/assets/ts/coverage/index.html` in the browser or is this somewhere else?

Yep, that's exactly it @i0sea . The file will reflect the coverage as of whenever you last ran Jest locally

2022-05-06 19:12 UTC, thecristen approved these changes

2022-05-06 19:13 UTC, merged