Add alerts to project pages
mbta/dotcom pull request #1302
Opened 2022-05-23 17:46 UTC by zovt

#### Summary of changes
**Asana Ticket:** [Display alerts list on project page](https://app.asana.com/0/385363666817452/1200671244979944/f)

**NOTE**: This also closes [this ticket](https://app.asana.com/0/385363666817452/1200311487753031/f)

![2022-05-23_13-34](https://user-images.githubusercontent.com/5061820/169875852-75a437e1-0745-41a5-b9d1-496bc8544c8e.png)
![2022-05-23_13-34_2](https://user-images.githubusercontent.com/5061820/169875866-ffed4500-fbad-42dd-a22c-d0a23058fd23.png)

Some changes from the design:
- The design calls for this section to be below the header image on the page. However, the header image comes back to us as a "section" of the content we get from the CMS. We could probably do some smarts to properly split the image from the rest of the sections and inject this section, but I think it'll be relatively tricky. Steve gave the go-ahead for keeping it at the top for now, and we can circle back to this later if need be.
- I changed the "Show / Hide Alerts" text to be a static "Details". The switch between "Show Alerts" and "Hide Alerts" was causing annoying visual shifting of the dropdown indicator, and I'm not aware of a good solution to set the width of the element to the greater of the two. If anyone has any ideas here, let me know.

2022-05-23 20:59 UTC, thecristen requested changes
I'd love to see a test added to cover the display of alerts! Otherwise looks pretty good.

2022-05-23 20:59 UTC, thecristen commented on apps/site/lib/site_web/templates/cms/page/_alerts.html.eex
> +    alerts = Enum.filter(@alerts, & alert_related?(paths, &1))
Could put this all this logic in the `page_content_view.ex`, e.g. `alerts = alerts_for_page(@alerts, @page)`

2022-05-24 14:13 UTC, zovt commented on apps/site/assets/css/_project.scss
> +
I think for now I'll leave it as is, but if there's major pushback from design review I'll go with something like this 👍

2022-05-24 15:42 UTC, zovt commented
Also, I think I'm going to open a separate feature branch for this 👍

2022-05-24 15:49 UTC, thecristen commented
> Also, I think I'm going to open a separate feature branch for this 👍

@zovt does that mean you don't want to merge this into master?

2022-05-24 15:49 UTC, thecristen approved these changes

2022-05-24 17:00 UTC, thecristen commented
Ah ok @zovt thanks for the context. That sounds good to me.

2022-05-24 17:59 UTC, merged