"News" section > "Press Releases" section
mbta/dotcom pull request #1318
Opened 2022-06-13 19:01 UTC by bfauble

#### Summary of changes
**Asana Ticket:** ["News" section > "Press Releases" section](https://app.asana.com/0/555089885850811/1202075661172628/f)

![image](https://user-images.githubusercontent.com/526017/173424907-fee130f8-03ac-4f44-b31e-c47f052ebb59.png)
![image](https://user-images.githubusercontent.com/526017/173424970-6fb6e5b5-b284-4d65-b309-2a80cd3ade10.png)

2022-06-14 19:57 UTC, i0sea reviewed
Looking at the mocks there's some padding on top of the icons.  xs screens may be limited to 3 press releases but I'm unsure if that's accurate. Otherwise LGTM

2022-06-14 19:57 UTC, i0sea commented on apps/site/test/site_web/views/page_view_test.exs
> +      # assert rendered |> Floki.find(".c-news-entry--large") |> Enum.count() == 2
Should this be uncommented or deleted?

2022-06-16 14:52 UTC, lund5000 commented
> xs screens may be limited to 3 press releases

Good catch, @i0sea! We added that detail to the events task but missed getting it into this one. 🙈 

@bfauble If it's not a quick update we can defer adding it, but it would be good to limit the list to three items at the xs breakpoint (six at higher breakpoints).

2022-06-22 18:38 UTC, thecristen requested changes
I'm ok merging this if we remove the soon-to-be-extraneous "upcoming events" link.

2022-06-24 16:13 UTC, merged