Add "Commuter Rail Alternatives" tab to OL schedule
mbta/dotcom pull request #1378
Opened 2022-08-17 15:03 UTC by i0sea

#### Summary of changes
**Asana Ticket:** [Add "Commuter Rail Alternatives" tab to OL schedule ](https://app.asana.com/0/555089885850811/1202792787402845/f)

Added a commuter rail alternatives tab to the orange line page. This contains a timetable of CR stops from South Station to Forest Hills and links to the needed stops north of South Station.

2022-08-17 15:19 UTC, lund5000 commented
Sweeeet. How much time do you think it would take to add the custom PDF links to https://cdn.mbta.com/sites/default/files/route_pdfs/2022-summer/2022-08-10-cr-hyde-park-forest-hills-ruggles-back-bay-south-station-ol-shutdown.pdf and https://cdn.mbta.com/sites/default/files/route_pdfs/2022-summer/2022-08-15-cr-oak-grove-malden-center-north-station-ol-shutdown.pdf described in the ticket? Should we do that as part of this PR or as a quick follow-up?

2022-08-17 15:26 UTC, lund5000 commented
Looking at this again, I'd also like some minor adjustments to the copy and headings:

- "at no charge" paragraph on its own at the top
- "North Side Alternatives" h2
- Haverhill link paragraph
- "South Side Alternatives" h2
- Slightly modified version of the timetable explanation: "This is a combined timetable for all commuter rail trains that will be running to south side Orange Line stations while service is suspended."
- Combined timetable and the rest of the page as it is now

![dev-green mbtace com_schedules_Orange_timetable_schedule_direction destination = schedule_direction direction_id =1 schedule_direction origin = (1)](https://user-images.githubusercontent.com/772939/185178833-65cfbb33-7098-48be-aebd-bf5832f04ed4.png)

2022-08-17 15:56 UTC, i0sea commented
> Sweeeet. How much time do you think it would take to add the custom PDF links to https://cdn.mbta.com/sites/default/files/route_pdfs/2022-summer/2022-08-10-cr-hyde-park-forest-hills-ruggles-back-bay-south-station-ol-shutdown.pdf and https://cdn.mbta.com/sites/default/files/route_pdfs/2022-summer/2022-08-15-cr-oak-grove-malden-center-north-station-ol-shutdown.pdf described in the ticket? Should we do that as part of this PR or as a quick follow-up?

@lund5000  I think this should be a quick follow up. Also think the pdfs come from the Siteweb endpoint so they'd have to put via an API I believe.

2022-08-17 16:03 UTC, i0sea commented
Also Direction picker isn't altering the table. Will investigate and make copy changes ⌨️

2022-08-17 21:34 UTC, thecristen requested changes
🔄

2022-08-17 21:34 UTC, thecristen commented on apps/site/lib/site_web/views/helpers.ex
> +        end
Are these headsigns backwards? It's making the direction picker say `Southbound -> South Station` whereas Forest Hills is south of South Station.

As a reference, on the line diagram, the southbound train goes to Forest Hills:

![image](https://user-images.githubusercontent.com/2136286/185246478-680f1c60-b29e-4fa2-8029-66ce481dde85.png)

2022-08-17 21:34 UTC, thecristen commented on apps/site/lib/site_web/controllers/schedule/timetable_controller.ex
> +        stop_ids = ["place-forhl","place-rugg", "place-bbsta", "place-sstat"]
I think this is backwards too. The timestamps should be increasing as we go down the column:

![image](https://user-images.githubusercontent.com/2136286/185246749-7fdc2650-5cd6-49a3-a252-e94b2203c2c6.png)

2022-08-17 21:34 UTC, thecristen commented on apps/site/lib/site_web/templates/schedule/_timetable.html.eex
> +    <a target="_blank" href="https://www.mbta.com/stops/place-north">North Station</a>
nitpick: use the url helpers  Phoenix provides, e.g. `href="<%= stop_path(@conn, :show, "place-north") %>"`

2022-08-18 13:44 UTC, lund5000 approved these changes
I think this is good to go once the direction & order issues Cristen raised are fixed.

2022-08-18 14:57 UTC, lund5000 commented on apps/site/lib/site_web/templates/schedule/_timetable.html.eex
> +    <a target="_blank" href="https://www.mbta.com/schedules/CR-Haverhill/timetable">Haverhill Line</a> trains will stop at
Good catch! 🎉

2022-08-18 18:53 UTC, thecristen approved these changes

2022-08-18 19:04 UTC, merged