feat: Updated ferry map
mbta/dotcom pull request #1430
Opened 2022-09-26 14:55 UTC by arkadyan

#### Summary of changes
**Asana Ticket:** [Update source URL for ferry map](https://app.asana.com/0/555089885850811/1202974987514982)

[[Please include a brief description of what was changed]](feat: Updated ferry map)

---

Before getting review, please check the following:

* [x] Does frontend functionality render and work correctly in IE?
* [x] Have we load-tested any new pages or internal API endpoints that will receive significant traffic? [See load testing docs](./../apps/site/load_tests/README.md)
* [x] Are interactive elements accessible to screen readers?
* [x] Have you checked for tech debt you can address in the area you're working in?
* [x] If this change involves routes, does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?
* [x] Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?

2022-09-26 23:01 UTC, thecristen requested changes
Sadly this URL is hardcoded in a unit test that's now failing! 🙊 Can you please resolve that (in whichever way you deem appropriate)?

2022-09-27 13:46 UTC, arkadyan commented
@thecristen It was way worse than hard-coding the result in the test: the test was calling implementation code for the "expectation". But in CI it was referencing an environment that hadn't been released to you. I adjusted all those tests to just test the type of the expected result.

2022-09-27 13:56 UTC, thecristen commented on apps/site/test/site/map_helpers_test.exs
> +        assert map_type |> map_pdf_url() |> is_binary()
I am wondering if this would pass even if the output URL is blank (e.g. `""`) -- `is_binary()` wouldn't know the difference no?

2022-09-27 14:00 UTC, arkadyan commented
@thecristen Thanks! Missed that there were two of them.

2022-09-27 16:13 UTC, thecristen approved these changes

2022-09-27 16:14 UTC, merged