Transit Near Me | Alerts not Showing
mbta/dotcom pull request #1522
Opened 2023-02-15 18:12 UTC by i0sea

#### Summary of changes

**Asana Ticket:** [Transit Near Me | Alerts not Showing](https://app.asana.com/0/385363666817452/1203879636893634/f)

Add alerts button to transit near me results

2023-02-17 21:32 UTC, i0sea commented
General question, should parameter for fetchAlerts be changed to url since that's what's usually passed by `useSWR`?

2023-02-17 21:54 UTC, thecristen commented on apps/site/assets/ts/tnm/components/RouteCard.tsx
> +        )}
This doesn't run

2023-02-21 15:30 UTC, thecristen requested changes
It works! These comments are mostly for readability

2023-02-21 15:30 UTC, thecristen commented on apps/site/assets/ts/tnm/components/RouteCard.tsx
> +  return alerts;
```suggestion
  return results.filter(isHighSeverityOrHighPriority);
```

This can be simplified!

2023-02-21 15:30 UTC, thecristen commented on apps/site/assets/ts/tnm/components/RouteCard.tsx
> +        )}
suggestion: this is nicely condensed, but sacrifices readability a bit. we can use some ES6 syntax ([object destructuring](https://javascript.info/destructuring-assignment)) to help us a bit here:

```typescript
// destructures the "data" property out of the response object and renames it to "alerts"
// alerts might be undefined here
const { data: alerts } = useSWR<Alert[]>(`${route.route.id}`, fetchAlerts);
```

Also you can assign a fallback value if the initial value is false with `||`. So you could pass in `alerts={alerts || []}` and it should work in the same manner as your `isDefined` function.

2023-02-22 14:24 UTC, thecristen requested changes
Looked at the Jest unit tests. `RoutesSidebarTest.tsx` and `RouteCardTest.tsx` are failing. You might need to update those tests to accommodate the new logic you introduced here.

2023-02-22 21:33 UTC, thecristen approved these changes

2023-02-22 21:36 UTC, merged