[Spike] Using the predictions refactor work in departures
mbta/dotcom pull request #1561
Opened 2023-04-04 17:52 UTC by thecristen

#### Summary of changes

**Asana Ticket:** [[Spike] Using the predictions refactor work in departures](https://app.asana.com/0/385363666817452/1204099052193042/f)

# Background

> **Note**
> The goal of this spike is to understand whether this prior streaming predictions work could be leveraged to display live departures for the new stops page.

Dotcom is working on a redesign of the stops pages ([random example page](https://dev.mbtace.com/stops/1112)). As with the current version, the new version will show upcoming departures using data we get from the V3 API's predictions.

A few months ago the Dotcom team put in substantial effort into reconsidering how we fetch and serve prediction data site-wide, culminating in **#1476 feat(Predictions): Subscribe to streaming updates by routeId and stopId**. You can go to that PR for the detailed diffs, but here are the key takeaways:
- Sets up a DynamicSupervisor for spinning up new API prediction streams (via the ServerSentEvents-driven streaming feature the V3 API offers) on-demand per route (later per route/stop/direction), handling parsing.
- Broadcasts updates to Phoenix.PubSub, which manages subscriptions to the streams, handles internal state, and broadcasts messages to..
- Sets up a Phoenix Channel to allow clients to subscribe to predictions updates

But other priorities took over and this wasn't merged in.

# This PR

## Incorporating the prior streaming predictions work

The prior work noted above is merged into this branch as the first commit. The second commit follows with a series of fixes and improvements:

- fix(Predictions.Parser): when determining “first time”, prefer departure time instead of arrival time. This more closely follows V3 API best practice with respect to what time we wish to display to riders.
- fixup(Predictions): update to new child supervisor syntax for `Predictions.PubSub`
- fix(Predictions.PredictionsPubSub): actually add subsequent subscriptions to state
- fix(Predictions.StreamSupervisor): actually use the pid that's registered, rather than the pid the registration is under (!)
- fix(SiteWeb.PredictionsChannel): filter out old predictions in `handle_info` rather than in initialization only
- fix(SiteWeb.PredictionsChannel): remove predictions with no trip information
- fix(SiteWeb.PredictionsChannel): remove predictions with null departure time, as those are likely to be arrivals to terminals that passengers can’t board anyway.
- Make all necessary updates to unit tests

## Frontend work around how we standardize subscribing to channels

To aid in this spike's effort I relied upon an earlier effort I'd made to **#1481 Consolidate channel handling** . We had duplicate ways to subscribe to channels in the frontend and that PR sought to streamline and simplify that. It's included here as the third commit, and followed with the fourth commit with some minor cleanup.

## Stop Page Redesign WIP

### refactor(StopPageRedesign): extract departures section

The fifth commit includes some light refactoring to the WIP redesigned stop page, mainly to scaffold out the components that are going to be fetching the streaming predictions.

### feat(StopPageDepartures): predictions POC

The sixth commit finally adds the predictions to the stop page, through a new React hook, `usePredictionsChannel`, that uses the `useChannel` abstraction introduced in the third commit.

I've additionally created placeholder components for displaying the prediction data. These can be viewed by enabling the feature flag to turn on the stops page redesign. You can enable the feature flag appending `active_flag=stops_redesign` to the URL, or by visiting `/_flags` and clicking the checkbox.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/2136286/229876360-dff2aa93-3fc5-47f1-82ed-635ec5141729.png">

Please consider all presentational aspects as out of scope for this PR. This is just meant to demonstrate the types and fidelity of data we now have in the frontend.

# Notes

Finally, I haven't load tested any this. What happens when tens of thousands of visitors try to view predictions on the North Station page at the same time? Since the stops page redesign work is still a WIP, I'm ok leaving this question for a future investigation.

---

#### General checks
* [x] **Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?** This is a good practice that can facilitate easier reviews.
* [x] **Testing.** Do the changes include relevant passing updates to tests? This includes updating screenshots. Preferably tests are run locally to verify that there are no test failures created by these changes, before opening a PR.
* [x] **Tech debt.** Have you checked for tech debt you can address in the area you're working in? This can be a good time to address small issues, or create Asana tickets for larger issues.

#### New endpoints, or non-trivial changes to current endpoints
* [ ] **Have we load-tested** any new pages or internal API endpoints that will receive significant traffic? [See load testing docs](./../apps/site/load_tests/README.md)

2023-04-05 14:44 UTC, kotva006 commented on apps/site/assets/ts/stop/components/StopPageRedesign.tsx
> +  );
nit-pick: The data fetching should be put in a reusable hook.

2023-04-14 18:27 UTC, thecristen commented
@arkadyan I must've written this PR description like ten times 😌 glad it was helpful in the end.
Your assessment is mostly correct - I do expect this will serve as the basis for subsequent work, but I **do** want get this merged. The redesign is behind a feature branch and we've been merging in the WIP as we go! Hope that helps!

2023-04-14 20:18 UTC, arkadyan requested changes
A bunch of comments here—sorry if I was being chatty. I think the biggest things are probably some data conversion and definitely more tests in a few places.

All that said, I think all my comments were on details and fine polish. Overall, I like this approach, and I'm very excited to see where this is all going. It seems like it's getting both more unified as well as more powerful and straightforward at the same time.

(Nitpick, but it sounds like you can remove the “wip” from the 3rd commit message since it’s ready to be merged.)

2023-04-14 20:18 UTC, arkadyan commented on apps/site/assets/ts/stop/components/DepartureTimes.tsx
> +export default DepartureTimes;
issue: This component could generally use some tests.

2023-04-14 20:18 UTC, arkadyan commented on apps/site/assets/ts/stop/components/DepartureTimes.tsx
> +const formatTime = (timeString: string, isCR: boolean): string => {
issue: This conditional time formatting seems important to test.

2023-04-14 20:18 UTC, arkadyan commented on apps/site/assets/ts/stop/components/DepartureTimes.tsx
> +    return (
suggestion (non-blocking): This feels like something that could be refactored out into a named, sub-component function.

2023-04-14 20:18 UTC, arkadyan commented on apps/site/assets/ts/stop/components/DepartureTimes.tsx
> +          <div key={headsign} className="departure-card__headsign">
suggestion (non-blocking): This also feels like something that could be refactored out into a named, sub-component function.

2023-04-14 20:18 UTC, arkadyan commented on apps/site/assets/ts/stop/components/DepartureTimes.tsx
> +        <button
question: Am I right in thinking that this button is missing an action? Maybe that's something that's coming later?
suggestion (non-blocking): If that's true, a quick comment might be useful to clarify.

2023-04-14 20:54 UTC, thecristen commented on apps/site/assets/ts/hooks/usePredictionsChannel.ts
> +export default usePredictionsChannel;
This could pretty easily be used in the line diagram! Probably in Transit Near Me as well.

2023-04-14 21:02 UTC, thecristen commented on apps/site/assets/ts/hooks/usePredictionsChannel.ts
> +interface PredictionsByHeadsign {
I think my thinking here was this was more of a niche type that's not as broadly relevant as say a `Stop`. Though now I notice we have lots of different `__something.d.ts` files for all sorts of use cases... 🤔

2023-04-14 21:08 UTC, thecristen commented on apps/site/assets/ts/stop/components/DepartureTimes.tsx
> +/* istanbul ignore next */
Istanbul is the test coverage tool used with Jest; since this piece isn't finalized I didn't want it to make our test coverage go down 😅

2023-04-14 21:54 UTC, thecristen commented on apps/site/assets/ts/stop/components/DepartureCard.tsx
> +          directionId={(direction_id as unknown) as DirectionId}
Yeah, going off of the `route.direction_destinations` object keys means they're always `strings`, but maybe hardcoding is the way to go here :/

2023-04-18 17:07 UTC, arkadyan commented on apps/site/assets/ts/hooks/usePredictionsChannel.ts
> +export default usePredictionsChannel;
Up to you, but might be worth some tickets. As in https://github.com/mbta/dotcom/pull/1481, I can imagine that consolidating everything onto a single usage pattern might have big dividends.

2023-04-18 17:25 UTC, arkadyan approved these changes
👍

2023-04-18 17:25 UTC, arkadyan commented on apps/site/assets/ts/helpers/__tests__/date-test.ts
> +describe("formatDepartureTime", () => {
👍

2023-04-18 17:25 UTC, arkadyan commented on apps/site/assets/ts/helpers/__tests__/date-test.ts
> +});
suggestion: It seems like there should be a second test case for CR.

2023-04-18 18:05 UTC, merged