Create endpoint to fetch amenities
mbta/dotcom pull request #1636
Opened 2023-06-14 20:28 UTC by i0sea

#### Summary of changes

**Asana Ticket:** [Create endpoint to fetch amenities](https://app.asana.com/0/385363666817452/1204807135759953/f)

---

Updated alerts by stop id fetcher to include all activities

#### General checks
* [ ] **Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?** This is a good practice that can facilitate easier reviews.
* [ ] **Testing.** Do the changes include relevant passing updates to tests? This includes updating screenshots. Preferably tests are run locally to verify that there are no test failures created by these changes, before opening a PR.
* [ ] **Tech debt.** Have you checked for tech debt you can address in the area you're working in? This can be a good time to address small issues, or create Asana tickets for larger issues.

#### New UI, or substantial UI changes
* [ ] **Cross-browser compatibility** is less of an issue now that we're no longer supporting IE, but changes still need to work as expected in Safari, Chrome, and Firefox.
* [ ] **Are interactive elements accessible?** This includes at minimum having [relevant keyboard interactions](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#keyboard-interaction) and [visible focus](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#visible-focus), but can also include verification with screen reader testing.
* [ ] **Other accessibility checks** such as sufficient [color constrast](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#color-contrast), or whether the layout holds up at 200% [zoom level](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#visible-focus).

#### New endpoints, or non-trivial changes to current endpoints
* [ ] **Have we load-tested** any new pages or internal API endpoints that will receive significant traffic? [See load testing docs](./../apps/site/load_tests/README.md)
* [ ] **If this change involves routes,** does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?

2023-06-15 19:28 UTC, thecristen reviewed
Might want to update this PR's name since you ended up not creating a new distinct endpoint.

Also, is there a particular route/stop we might want to look at to see some amenity alerts? :)

2023-06-16 15:09 UTC, i0sea commented
@thecristen  Will have to add  `console.log(alerts)` into `StationInformation.tsx` and visit broadway or any station mentioned at https://dev-green.mbtace.com/alerts/access . Was debating adding in an alert prop for each of the amenity card and rendering the alert name in the card but that seems outside the bounds of this ticket.

2023-06-16 15:31 UTC, thecristen requested changes
🥳 Looks solid, can you add a test for `isAmenityAlert`?

2023-06-16 18:42 UTC, thecristen approved these changes

2023-06-16 19:02 UTC, merged