feat(StopPageDepartures): fetch predictions at top level
mbta/dotcom pull request #1650
Opened 2023-06-27 20:18 UTC by thecristen

#### Summary of changes

No ticket. It moves our call to predictions higher up in the tree, making one websocket connection for all the predictions, instead of one per route/direction.

---

#### General checks
* [ ] **Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?** This is a good practice that can facilitate easier reviews.
* [ ] **Testing.** Do the changes include relevant passing updates to tests? This includes updating screenshots. Preferably tests are run locally to verify that there are no test failures created by these changes, before opening a PR.
* [ ] **Tech debt.** Have you checked for tech debt you can address in the area you're working in? This can be a good time to address small issues, or create Asana tickets for larger issues.

#### New UI, or substantial UI changes
* [ ] **Cross-browser compatibility** is less of an issue now that we're no longer supporting IE, but changes still need to work as expected in Safari, Chrome, and Firefox.
* [ ] **Are interactive elements accessible?** This includes at minimum having [relevant keyboard interactions](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#keyboard-interaction) and [visible focus](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#visible-focus), but can also include verification with screen reader testing.
* [ ] **Other accessibility checks** such as sufficient [color constrast](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#color-contrast), or whether the layout holds up at 200% [zoom level](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#visible-focus).

#### New endpoints, or non-trivial changes to current endpoints
* [ ] **Have we load-tested** any new pages or internal API endpoints that will receive significant traffic? [See load testing docs](./../apps/site/load_tests/README.md)
* [ ] **If this change involves routes,** does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?

2023-06-28 13:55 UTC, kotva006 commented on apps/site/assets/ts/stop/components/StopPageDepartures.tsx
> +    departures: DepartureInfo[] | null | undefined
So the one downside to this approach is that the predictions will not update on the realtime list.  The value of this property `departures` is set when the user clicks on a row.  When the `usePredictionsChannel` updates with new predictions it never gets a chance to pass them to the realtime list.  The user is on a different component, and this predictions values are never passed to the list directly.

2023-07-13 15:22 UTC, i0sea requested changes

2023-07-13 15:22 UTC, i0sea commented on apps/site/assets/ts/hooks/__tests__/usePredictionsChannelTest.tsx
> +      usePredictionsChannel({
nitpick: can a test be added that only uses `stopId`?

2023-07-13 15:22 UTC, i0sea commented on apps/site/assets/ts/stop/__tests__/DepartureListTest.tsx
>    it("should render a schedule when no predictions available", () => {
add test for rendering prediction if there are no schedules

2023-07-13 19:18 UTC, thecristen commented on apps/site/assets/ts/hooks/usePredictionsChannel.ts
> +  const keysWithValues = Object.entries({
It does! Nice catch, using an empty string is probably suboptimal... will update to not try to join channels..

2023-07-13 20:05 UTC, i0sea approved these changes
🚀

2023-07-13 20:07 UTC, merged