fix: move icons to `/priv/static` to aid precompilation + webpack updates
mbta/dotcom pull request #1949
Opened 2024-03-28 19:43 UTC by thecristen

#### Summary of changes

**Asana Ticket:** [Investigate asset compilation bugginess](https://app.asana.com/0/555089885850811/1206658096186582/f)

I've determined the cause of the issue we'd all seen was that the precompilation that was creating the `DotcomWeb.ViewHelpers.svg/1` function clauses relies on every SVG icon already being present in `/priv/static`, but our current handling of assets wouldn't move those icons from `/assets/static` to `/priv/static` until when building the assets for production.

Because the set of icons Dotcom uses hardly ever changes, I felt like it made more sense to just relocate them to `/priv` and leave them there, rather than relying on Webpack copying them over. Most of the changes in this PR are from that move.

I also updated all the Webpack-related dependencies to latest. A few small changes to other files are from that.

---

#### General checks
* [x] **Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?** This is a good practice that can facilitate easier reviews.
* [ ] **Testing.** Do the changes include relevant passing updates to tests? This includes updating screenshots. Preferably tests are run locally to verify that there are no test failures created by these changes, before opening a PR.
* [x] **Tech debt.** Have you checked for tech debt you can address in the area you're working in? This can be a good time to address small issues, or create Asana tickets for larger issues.

2024-03-29 03:24 UTC, thecristen commented on assets/css/_events.scss
> +    margin: 0 (-$base-spacing);
This was flagged by Webpack dev server.

2024-03-29 03:26 UTC, thecristen commented on assets/webpack.config.base.js
> +                  active: false
This was added due to a changed default in the `svgo-loader` upgrade.

2024-03-29 03:27 UTC, thecristen commented on assets/webpack.config.base.js
> +                    enableClientSidePolyfills: true
This was added due to a changed default in the `postcss-preset-env` upgrade.

2024-03-29 03:28 UTC, thecristen commented on assets/webpack.config.dev.js
> +        writeToDisk: true
This changes makes Webpack write everything to `/priv/static` in dev mode, as opposed to only the CSS

2024-03-29 03:29 UTC, thecristen commented on upload_assets.sh
> -aws s3 sync "$STATIC_DIR/fonts" s3://mbta-dotcom/fonts --size-only --exclude "*" --include "*.svg" --cache-control=$CACHE_CONTROL --content-type "image/svg+xml"
We don't have any of these extensions in our `/fonts`

2024-03-29 15:36 UTC, anthonyshull commented
@thecristen this doesn't work with docker compose.

2024-03-29 15:38 UTC, anthonyshull requested changes
This branch doesn't work with docker compose. Running `docker compose -f deploy/dev.yml up -d` both copies of dotcom fail.

`npm ERR! Missing script: "build"`

2024-04-16 21:13 UTC, thecristen commented
> `npm ERR! Missing script: "build"`

This was happening to me too. The only thing that fixed it was nuking everything via `docker system prune -a` 😵 

Anyway, I currently have this working locally with both copies of Dotcom running 🥳

2024-04-22 13:20 UTC, anthonyshull approved these changes

2024-04-22 19:51 UTC, merged