fix(Credo): Reduce function nesting
mbta/dotcom pull request #2083
Opened 2024-05-31 15:19 UTC by kotva006

https://app.asana.com/0/home/1201123880594717/1207286684779746

Refactor to reduce function nesting

2024-05-31 17:06 UTC, anthonyshull requested changes

2024-05-31 17:06 UTC, anthonyshull commented on lib/dotcom_web/controllers/trip_plan_controller.ex
> +      |> Fares.get_fare_by_type(:highest_one_way_fare)
Not sure why it didn't, but Credo should be flagging the use of pipe here. We can just call the function since there is only one pipe.

2024-05-31 17:06 UTC, anthonyshull commented on lib/dotcom_web/views/page_content_view.ex
> +  end
Can use pattern matching to remove that first level of if/else.

2024-05-31 17:06 UTC, anthonyshull commented on lib/mix/tasks/header_footer.ex
> +      if lang_code != "en" do
Can use pattern matching to remove this if.

2024-05-31 17:06 UTC, anthonyshull commented on lib/mix/tasks/header_footer.ex
> +        filenm =
Variables aren't immutable. We can reuse the word `filename`.

2024-05-31 17:06 UTC, anthonyshull commented on lib/mix/tasks/header_footer.ex
> +    defp files_list_reducer(filename, path, base_path, acc) do
This function is doing a lot. It's hard to read. It can be broken out further to be more clear.

2024-06-05 14:11 UTC, kotva006 commented on lib/dotcom_web/controllers/schedule_controller.ex
> +  end
Future helpful feedback could include possible names of the functions, or why the name is considered bad and what to avoid in the future

2024-06-05 14:11 UTC, kotva006 commented on lib/dotcom_web/controllers/schedule_controller.ex
> +  defp map_trip_to_time(%Schedule{time: t, trip: trip}) do
Future helpful feedback could include possible names of the functions, or why the name is considered bad and what to avoid in the future

2024-06-07 14:24 UTC, anthonyshull approved these changes
👍

2024-06-07 14:27 UTC, merged