feat(ContentSecurityPolicy): Add a content security policy (#2094)
mbta/dotcom pull request #2102
Opened 2024-06-20 21:36 UTC by kotva006

Re-Adding the CSP with more resources covered
https://app.asana.com/0/555089885850811/1207405407228256

2024-06-21 18:20 UTC, thecristen requested changes

2024-06-21 18:20 UTC, thecristen commented on config/runtime.exs
> +               "frame-src 'self' data.mbta.com data.mbta.com www.youtube.com www.google.com cdn.knightlab.com livestream.com www.instagram.com"
**typo**: got data.mbta.com on here twice

2024-06-21 18:20 UTC, thecristen commented on config/runtime.exs
>                 "connect-src 'self' *.googleapis.com #{sentry_dsn_host || ""}",
I believe `analytics.google.com` needs to be added here to `connect-src` too

2024-06-21 18:20 UTC, thecristen commented on config/runtime.exs
> +               "img-src 'self' cdn.mbta.com #{System.get_env("STATIC_HOST", "")} #{System.get_env("CMS_API_BASE_URL", "")} *.google.com *.googleapis.com *.gstatic.com *.s3.amazonaws.com data: i.ytimg
question: do we need the `*.s3.amazonaws.com` one? As far as I could tell the only place we need this is for rendering map image tiles on dev (that URL is elsewhere in our config, `mbta-map-tiles-dev.s3.amazonaws.com`).

2024-06-21 18:37 UTC, thecristen commented on config/runtime.exs
>                 "connect-src 'self' *.googleapis.com #{sentry_dsn_host || ""}",
whoops looks like it's `www.google-analytics.com` (and needs to be in `script-src` as well as `connect-src`)

2024-06-24 17:43 UTC, thecristen requested changes
From the homepage

<img width="848" alt="image" src="https://github.com/mbta/dotcom/assets/2136286/ee87585e-c76e-4d23-a156-8beb3441600e">

From the Sumner tunnel page (`/diversions/alternative-travel-options-during-the-2024-sumner-tunnel-closure`)

<img width="910" alt="image" src="https://github.com/mbta/dotcom/assets/2136286/326e63bb-caed-4b2c-a09e-31a0e6b7a5f2">

2024-06-24 18:10 UTC, kotva006 commented
![Screenshot 2024-06-24 at 1 10 09 PM](https://github.com/mbta/dotcom/assets/2679229/453a8a02-c598-40b9-8ec3-dc90488fde1e)
Homepage

2024-06-24 20:48 UTC, thecristen approved these changes
let's give it a go! 🚀

2024-06-27 19:55 UTC, merged