chore: add DotcomWeb.CoreComponents
mbta/dotcom pull request #2157
Opened 2024-08-22 19:19 UTC by bklebe

#### Summary of changes

**Asana Ticket:** [Import the set of base `Phoenix.Components`](https://app.asana.com/0/555089885850811/1207828528645183/f)

Supersedes #2136. 

---

#### General checks
* [ ] **Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?** This is a good practice that can facilitate easier reviews.
* [ ] **Testing.** Do the changes include relevant passing updates to tests? This includes updating screenshots. Preferably tests are run locally to verify that there are no test failures created by these changes, before opening a PR.
* [ ] **Tech debt.** Have you checked for tech debt you can address in the area you're working in? This can be a good time to address small issues, or create Asana tickets for larger issues.

#### New UI, or substantial UI changes
* [ ] **Cross-browser compatibility** is less of an issue now that we're no longer supporting IE, but changes still need to work as expected in Safari, Chrome, and Firefox.
* [ ] **Are interactive elements accessible?** This includes at minimum having [relevant keyboard interactions](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#keyboard-interaction) and [visible focus](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#visible-focus), but can also include verification with screen reader testing.
* [ ] **Other accessibility checks** such as sufficient [color constrast](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#color-contrast), or whether the layout holds up at 200% [zoom level](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#visible-focus).

#### New endpoints, or non-trivial changes to current endpoints
* [ ] **Have we load-tested** any new pages or internal API endpoints that will receive significant traffic? [See load testing docs](./../load_tests/README.md)
* [ ] **If this change involves routes,** does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?

2024-08-22 20:06 UTC, bklebe commented
Not totally sure how to test this, there are at least no more Webpack errors. Let me know what you think —

2024-08-22 22:10 UTC, thecristen requested changes
super cool!
- can you please add `import DotcomWeb.CoreComponents` to the `DotcomWeb` `view_helpers` block? then the components will be easy to invoke anywhere!
- I tried out the `<.input />` and the styling doesn't seem to be quite working, I just get a mostly plain HTML output. Maybe we're needing an import statement somewhere to bring the Tailwind classes in? Or did you want to leave that for a followup PR?

2024-08-26 18:42 UTC, bklebe commented
@thecristen 

> can you please add import DotcomWeb.CoreComponents to the DotcomWeb view_helpers block? then the components will be easy to invoke anywhere!

This sounds like a good idea, but it would require either renaming `icon` component in CoreComponents to `hero_icon` or something, or renaming all the other functions called `icon` that we use in views, e.g.: https://github.com/search?q=repo%3Ambta%2Fdotcom+def+icon&type=code. Let me know which one you want me to do, or whether I should leave it for a followup.

Still trying to figure out why Tailwind isn't styling the components properly, I'll keep you posted.

2024-08-26 19:13 UTC, bklebe commented
> your link doesn't have the search term quoted

That was intentional because some are def and some are defp, but with the benefit of hindsight, here's a less stupid search: https://github.com/search?q=repo%3Ambta%2Fdotcom+%28%22def+icon%28%22+OR+%22defp+icon%28%22%29&type=code

2024-08-26 19:26 UTC, thecristen commented
@bklebe oh snap! Let's rename it (and any others)

2024-08-29 02:01 UTC, thecristen requested changes
I had to add an import of the Tailwind CSS into our CSS to get it to style the components, did you forget it?

1. Import it into the beginning of the `app.scss` file:
```scss
@import "~tailwindcss/base";
@import "~tailwindcss/components";
@import "~tailwindcss/utilities";
```

I also figured out Tailwind apparently includes some opinionated base styles, some of which conflict with ours. So you'll need to do this too:

2. Disable Tailwind's "Preflight" feature with [these instructions](https://tailwindcss.com/docs/preflight#disabling-preflight)

Curious to see this work on a deployment too.

2024-08-30 15:09 UTC, thecristen requested changes
Just a few spots in the core components that missed the Tailwind class prefixing!

Works locally but doesn't seem to the working for the prod build, feel free to use dev-blue to test out stuff!

2024-08-30 15:09 UTC, thecristen commented on lib/dotcom_web/components/core_components.ex
> +      ]}
missed some prefixing here!

2024-08-30 15:09 UTC, thecristen commented on lib/dotcom_web/components/core_components.ex
> +      ]}
missed some prefixing here too

2024-08-30 15:09 UTC, thecristen commented on lib/dotcom_web/components/core_components.ex
> +        ]}
more prefixing!

2024-08-30 15:09 UTC, thecristen commented on lib/dotcom_web/components/core_components.ex
> +        ]}
missing prefixes

2024-08-30 15:09 UTC, thecristen commented on lib/dotcom_web/components/core_components.ex
> +      <div>
Missing prefixes here

2024-08-30 15:09 UTC, thecristen commented on lib/dotcom_web/components/core_components.ex
> +              class={["relative p-0", @row_click && "hover:cursor-pointer"]}
missed prefix here

2024-08-30 15:09 UTC, thecristen commented on lib/dotcom_web/components/core_components.ex
> +                <span class={["relative", i == 0 && "font-semibold text-zinc-900"]}>
Missed prefix here

2024-08-30 15:09 UTC, thecristen commented on lib/dotcom_web/components/core_components.ex
> +         "opacity-100 translate-y-0 sm:scale-100"}
I think these are all CSS class names? They need prefixes

2024-08-30 15:09 UTC, thecristen commented on lib/dotcom_web/components/core_components.ex
> +    |> JS.add_class("overflow-hidden", to: "body")
missing prefixes

2024-08-30 15:09 UTC, thecristen commented on lib/dotcom_web/templates/page/index.html.eex
> +<div class="index tw-green">
Hahaha I didn't even notice this, it should've been way obvious 😂

2024-08-30 15:09 UTC, thecristen commented on lib/dotcom_web/templates/page/index.html.eex
> +<div class="index tw-green">
But I suppose `.green` isn't a real Tailwind class anyhow. Let's remove it.

2024-08-30 15:10 UTC, thecristen commented on lib/dotcom_web/templates/page/index.html.eex
> +<div class="index tw-green">
Oh, didn't realize you just added this, can disregard 😅

2024-08-30 20:08 UTC, thecristen approved these changes
FYI it's hard to tell what's changed between each of my reviews -- I recommend not squash+force-pushing after reviewing's begun. Anyhow, from what I can tell all the pieces are in place! 💯

2024-08-30 20:09 UTC, merged