Account for non-existing schedule route id for the Green Line
mbta/dotcom pull request #660
Opened 2020-10-29 13:17 UTC by alicia-mbta

#### Summary of changes
**Asana Ticket:** [🐞 Elixir.UndefinedFunctionError: function nil.route/0 is undefined](https://app.asana.com/0/385363666817452/1185865721068541)

Another bug involving trip info. This fix avoids getting a `500` error

2020-10-29 21:45 UTC, thecristen requested changes
Looks good on first glance! Let's not commit the formatting improvement to `VoteMap` though, since we'll be reverting that code soon.

2020-10-30 12:01 UTC, alicia-mbta commented
That was just the linter 😄 
Relatedly, I also noticed that the build fails because there is not enough code coverage due to the new "polling location finder" work (I believe).
I think this bug fix is a "nice to have" so it probably can wait to be merged after the revert.
Let me know what you think.

2020-10-30 14:55 UTC, thecristen commented
Gotcha. You're correct about the coverage failure reason. I agree with you on the wait - and I'll re-review then too :)

2020-11-18 22:16 UTC, thecristen commented on apps/site/lib/site_web/controllers/schedule/finder_api.ex
> +      schedule.route.id
I think [CodeCov wants a new test to cover this piece](https://codecov.io/gh/mbta/dotcom/src/19b90a0c42932ac61a2fcb52d53156098e008cb6/apps/site/lib/site_web/controllers/schedule/finder_api.ex), maybe that'll make it pass?

2020-11-25 00:47 UTC, thecristen approved these changes

2020-11-25 14:27 UTC, merged