PSL polish
mbta/dotcom pull request #833
Opened 2021-03-08 23:15 UTC by alicia-mbta

Polish work for the Proposed Sales Location page:

- Minor tweaks (increase radius, rewording sentences).
- sort locations by distance
- stronger address validation to accept a string with different location formats (address or lat/lon).

2021-03-09 00:33 UTC, alicia-mbta commented on apps/site/lib/site_web/templates/fare_transformation/proposed_sales_locations.html.eex
> +        <p><b>The address you entered is more than 100 miles from the nearest proposed sales location. Please use an address that's closer to an MBTA service area.</b></p>
This specific text might potentially change after Yinka and Jess agree on it.

2021-03-11 14:51 UTC, hannahpurcell requested changes
I like that the input box only uses addresses now!  It looks great, and the magnifying glass always works ✅ 

I've been using "Boston Landing" (a location in Brighton) as my test location.  The results in prod are correct, the first 3 being:  Boston Landing, Arthur St @ Guest St - Stop & Shop, and Brighton Ave @ Cambridge St.  I confirm with the map that these are the 3 closest PSLs to Boston Landing itself.  ✅ 

Dev-blue is showing a different 3 results, farther from the place of origin.  Not yet sure why this is happening  🤔 but is it related to the conversion of placename to coordinates, or vice versa?

2021-03-11 16:37 UTC, alicia-mbta commented
> Dev-blue is showing a different 3 results, farther from the place of origin. Not yet sure why this is happening 🤔 but is it related to the conversion of placename to coordinates, or vice versa?

Good observation! I looked into it and the difference seems to be because of the increase from 10 to 100 miles 😞
I'm not sure why though, since I also added the option to sort by distance...I'll see if I can dig deeper.

2021-03-11 16:47 UTC, alicia-mbta commented
UPDATE: I should sort, then slice 🤦‍♀️

2021-03-11 18:34 UTC, thecristen reviewed
I like that you moved `SiteWeb.Plugs.TransitNearMe.formatted_address` to `GoogleMaps.Geocode`... would it make sense to move `SiteWeb.FareController.calculate_position` and/or `SiteWeb.FareTransformationController.check_address` there as well?

2021-03-11 19:00 UTC, alicia-mbta commented
> I like that you moved `SiteWeb.Plugs.TransitNearMe.formatted_address` to `GoogleMaps.Geocode`... would it make sense to move `SiteWeb.FareController.calculate_position` and/or `SiteWeb.FareTransformationController.check_address` there as well?

Yes! I didn't think of that; I'll move those as well.

2021-03-11 19:03 UTC, alicia-mbta commented on apps/util/lib/position.ex
> +defimpl Util.Position, for: [Map, Fares.ProposedLocations.Location] do
Yes, makes sense to do it that way -- maybe I was just trying to save lines of code 😅

2021-03-15 14:17 UTC, hannahpurcell approved these changes
Looks great to me!

2021-03-15 14:49 UTC, thecristen approved these changes

2021-03-15 15:06 UTC, merged