Add a toggle to switch between list and calendar views
mbta/dotcom pull request #861
Opened 2021-03-26 18:56 UTC by alicia-mbta

#### Summary of changes
**Asana Ticket:** [Add toggle between views to navigation](https://app.asana.com/0/555089885850811/1199915858612067)

In desktop mode only, we can now switch between views:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/61979382/112679284-5df11b00-8e42-11eb-8566-4a2bfea31a2d.png">

2021-04-01 13:08 UTC, hannahpurcell requested changes
Ooooo it looks and works soooo nicely!   I'm loving it.  But first, accessibility adjustments

2021-04-01 13:08 UTC, hannahpurcell commented on apps/site/lib/site_web/templates/event/index.html.eex
> +        <% end %>
Each button is available to screen readers, but is just called "button".  Give the buttons a descriptive label (I think using `aria-label`?)

2021-04-01 20:08 UTC, hannahpurcell approved these changes
Looks great!  One adjustment that isn't a deal-breaker.  The formatting of the page is a little different with and without `calendar=true` in the URL.

<img width="760" alt="Screen Shot 2021-04-01 at 4 01 47 PM" src="https://user-images.githubusercontent.com/69368883/113347871-cdb04b80-9303-11eb-9f51-518b2f656439.png">
<img width="760" alt="Screen Shot 2021-04-01 at 4 01 52 PM" src="https://user-images.githubusercontent.com/69368883/113347872-ce48e200-9303-11eb-9226-6cf64783ece3.png">

2021-04-02 12:21 UTC, alicia-mbta commented
Good catch! Fixing that.

2021-04-02 14:31 UTC, hannahpurcell approved these changes
Yeah, looks good!

2021-04-02 15:23 UTC, merged