Hp/event page links without js
mbta/dotcom pull request #902
Opened 2021-04-26 17:45 UTC by hannahpurcell

#### Summary of changes
**Asana Ticket:** [With js disabled, "Jump to"' links don't do anything (Firefox on Mac)](https://app.asana.com/0/555089885850811/1200108181856603)

Left-hand links all add a "#" to the url that helps the page scroll even when JS is disabled.  When JS is disabled, the nav dropdowns are non-functional, so those have been hidden for now.

---

Before getting review, please check the following:

* [x] Does frontend functionality render and work correctly in IE?  **Unfortunately cannot test disabled JS because BrowserStack won't let me disable it...  but enabled JS looks fine**
* [ ] Are interactive elements accessible to screen readers?

2021-04-27 14:30 UTC, alicia-mbta requested changes

2021-04-27 14:30 UTC, alicia-mbta commented on apps/site/lib/site_web/views/event_view.ex
> +  end
Thanks for the clean refactor 🙏

2021-04-27 15:11 UTC, hannahpurcell commented on apps/site/lib/site_web/templates/event/_year_select.html.eex
> +        value: build_nav_path(@conn, @month, year),
Oh ok!  I expected the other way around but understand why starting at the beginning of the year would make sense.  I'll update it 👍

2021-04-27 21:01 UTC, thecristen reviewed
Just a comment to add to Alicia's! :)

2021-04-28 13:01 UTC, hannahpurcell commented on apps/site/assets/css/_events.scss
> +  &.js {
Oh so cool!!

2021-04-28 19:45 UTC, alicia-mbta approved these changes

2021-04-29 01:30 UTC, thecristen approved these changes

2021-04-29 19:52 UTC, merged